"""Jinja environment construction and README rendering."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from jinja2 import (
    BaseLoader,
    ChoiceLoader,
    Environment,
    FileSystemLoader,
    PackageLoader,
    StrictUndefined,
    TemplateNotFound,
)

from readwright.badges import BadgeRegistry, apply_style, shield
from readwright.changelog import latest_entries
from readwright.config import DEFAULT_TEMPLATE, Config, user_templates_dir
from readwright.helpers import Helpers
from readwright.images import ImageHelper
from readwright.toc import FENCE, insert_toc, toc_token

BASE_TEMPLATE = "base.md.j2"
MARKER_PREFIX = "<!-- generated by readwright"


def collapse_blank_lines(text: str) -> str:
    """Squeeze runs of blank lines down to one, leaving fenced code blocks untouched."""
    lines: list[str] = []
    in_fence = False
    previous_blank = False
    for line in text.splitlines():
        if FENCE.match(line):
            in_fence = not in_fence
        blank = not in_fence and line.strip() == ""
        if blank and previous_blank:
            continue
        lines.append(line)
        previous_blank = blank
    result = "\n".join(lines)
    return result.strip("\n") + "\n"


def marker(template_name: str) -> str:
    return f"{MARKER_PREFIX} from {template_name}; edit the template, not this file -->\n"


class TrackingLoader(BaseLoader):
    """Delegates to another loader and records which template names it served."""

    def __init__(self, label: str, inner: BaseLoader) -> None:
        self.label = label
        self.inner = inner
        self.served: list[str] = []

    def get_source(self, environment: Environment, template: str):  # type: ignore[override]
        source = self.inner.get_source(environment, template)
        self.served.append(template)
        return source

    def list_templates(self) -> list[str]:
        return self.inner.list_templates()


@dataclass
class RenderResult:
    text: str
    template_name: str
    warnings: list[str] = field(default_factory=list)
    user_templates: list[str] = field(default_factory=list)
    sources: dict[str, str] = field(default_factory=dict)


def loader_for(spec: str, root: Path) -> BaseLoader:
    """Build a loader from a config `templates:` entry: a path or `pkg:<package>[/subdir]`."""
    if spec.startswith("pkg:"):
        package, _, subdir = spec[4:].partition("/")
        return PackageLoader(package, subdir or "templates")
    path = Path(spec)
    return FileSystemLoader(str(path if path.is_absolute() else root / path))


class Renderer:
    def __init__(
        self,
        root: Path,
        config: Config,
        warn: Callable[[str], None] | None = None,
        user_templates: Path | None = None,
    ) -> None:
        self.root = Path(root)
        self.config = config
        self.warnings: list[str] = []
        self._external_warn = warn
        self.badges = BadgeRegistry(config)
        self.images = ImageHelper(self.root, config, warn=self._warn)
        self.helpers = Helpers(self.root, config, warn=self._warn)
        self.loaders: list[TrackingLoader] = [
            TrackingLoader(
                "repo", FileSystemLoader([str(self.root / "templates"), str(self.root)])
            ),
            *[TrackingLoader(spec, loader_for(spec, self.root)) for spec in config.templates],
            TrackingLoader(
                "user",
                FileSystemLoader(str(user_templates if user_templates else user_templates_dir())),
            ),
            TrackingLoader("readwright", PackageLoader("readwright", "templates")),
        ]
        self.user_loader = next(ld for ld in self.loaders if ld.label == "user")
        self.env = self._build_env()

    def _warn(self, message: str) -> None:
        self.warnings.append(message)
        if self._external_warn:
            self._external_warn(message)

    def _build_env(self) -> Environment:
        env = Environment(
            loader=ChoiceLoader(list(self.loaders)),
            undefined=StrictUndefined,
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
            autoescape=False,
        )
        env.globals.update(
            badge=self.badges.render,
            badges=self.badges.render_all,
            donate_badges=self.badges.render_donate,
            shield=self._styled_shield,
            screenshot=self.images.screenshot,
            screenshots=self.images.screenshots,
            image=self.images.image,
            has_screenshots=self.images.has_screenshots,
            toc=toc_token,
            changelog=lambda n=1, path=None, level=3: latest_entries(self.root, n, path, level),
            project=self.config.project,
            vars=self.config.vars,
            config=self.config,
            **self.helpers.as_globals(),
        )
        return env

    def _styled_shield(self, *args, **kwargs) -> str:
        style = kwargs.pop("style", None) or self.config.badges_style
        return apply_style(shield(*args, **kwargs), style)

    def source_label(self, name: str) -> str:
        for loader in self.loaders:
            try:
                loader.inner.get_source(self.env, name)
            except TemplateNotFound:
                continue
            return loader.label
        raise TemplateNotFound(name)

    def resolve_template_name(self) -> str:
        name = self.config.template
        try:
            self.env.get_template(name)
        except TemplateNotFound:
            if name != DEFAULT_TEMPLATE:
                raise
            return BASE_TEMPLATE
        return name

    def render(self) -> RenderResult:
        self.warnings.clear()
        for loader in self.loaders:
            loader.served.clear()
        name = self.resolve_template_name()
        body = self.env.get_template(name).render()
        text = marker(name) + collapse_blank_lines(insert_toc(body))
        return RenderResult(
            text=text,
            template_name=name,
            warnings=list(self.warnings),
            user_templates=list(self.user_loader.served),
            sources={name: ld.label for ld in self.loaders for name in ld.served},
        )
