<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <PackageId>DotTool.Cli</PackageId>
    <Version>2.1.0</Version>
    <Description>A .NET global tool for scaffolding project templates</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
