"""Jinja environment construction and README rendering."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from jinja2 import (
    BaseLoader,
    ChoiceLoader,
    Environment,
    FileSystemLoader,
    PackageLoader,
    StrictUndefined,
    TemplateNotFound,
)

from mkreadme.badges import BadgeRegistry, shield
from mkreadme.config import DEFAULT_TEMPLATE, Config, user_templates_dir
from mkreadme.images import ImageHelper
from mkreadme.toc import TOC_TOKEN, insert_toc

BASE_TEMPLATE = "base.md.j2"
MARKER_PREFIX = "<!-- generated by mkreadme"


def marker(template_name: str) -> str:
    return f"{MARKER_PREFIX} from {template_name}; edit the template, not this file -->\n"


class TrackingLoader(BaseLoader):
    """Delegates to another loader and records which template names it served."""

    def __init__(self, label: str, inner: BaseLoader) -> None:
        self.label = label
        self.inner = inner
        self.served: list[str] = []

    def get_source(self, environment: Environment, template: str):  # type: ignore[override]
        source = self.inner.get_source(environment, template)
        self.served.append(template)
        return source

    def list_templates(self) -> list[str]:
        return self.inner.list_templates()


@dataclass
class RenderResult:
    text: str
    template_name: str
    warnings: list[str] = field(default_factory=list)
    user_templates: list[str] = field(default_factory=list)


class Renderer:
    def __init__(
        self,
        root: Path,
        config: Config,
        warn: Callable[[str], None] | None = None,
        user_templates: Path | None = None,
    ) -> None:
        self.root = Path(root)
        self.config = config
        self.warnings: list[str] = []
        self._external_warn = warn
        self.badges = BadgeRegistry(config)
        self.images = ImageHelper(self.root, config, warn=self._warn)
        self.user_loader = TrackingLoader(
            "user",
            FileSystemLoader(str(user_templates if user_templates else user_templates_dir())),
        )
        self.env = self._build_env()

    def _warn(self, message: str) -> None:
        self.warnings.append(message)
        if self._external_warn:
            self._external_warn(message)

    def _build_env(self) -> Environment:
        loaders: list[BaseLoader] = [
            FileSystemLoader([str(self.root / "templates"), str(self.root)]),
            self.user_loader,
            PackageLoader("mkreadme", "templates"),
        ]
        env = Environment(
            loader=ChoiceLoader(loaders),
            undefined=StrictUndefined,
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
            autoescape=False,
        )
        env.globals.update(
            badge=self.badges.render,
            badges=self.badges.render_all,
            donate_badges=self.badges.render_donate,
            shield=shield,
            screenshot=self.images.screenshot,
            screenshots=self.images.screenshots,
            image=self.images.image,
            has_screenshots=self.images.has_screenshots,
            toc=lambda: TOC_TOKEN,
            project=self.config.project,
            vars=self.config.vars,
            config=self.config,
        )
        return env

    def resolve_template_name(self) -> str:
        name = self.config.template
        try:
            self.env.get_template(name)
        except TemplateNotFound:
            if name != DEFAULT_TEMPLATE:
                raise
            return BASE_TEMPLATE
        return name

    def render(self) -> RenderResult:
        self.warnings.clear()
        self.user_loader.served.clear()
        name = self.resolve_template_name()
        body = self.env.get_template(name).render()
        text = marker(name) + insert_toc(body)
        if not text.endswith("\n"):
            text += "\n"
        return RenderResult(
            text=text,
            template_name=name,
            warnings=list(self.warnings),
            user_templates=list(self.user_loader.served),
        )
