from pathlib import Path

import pytest

from readwright.config import resolve
from readwright.renderer import Renderer

EXAMPLES = Path(__file__).resolve().parent.parent / "examples"
TEMPLATELESS = {"config-only", "rust-cli", "go-cli", "dotnet-tool", "node-cli"}
EXPECTATIONS = {
    "kitchen-sink": [
        "# demo-tool",
        "style=flat-square",
        "ko-fi.com/octocat",
        "- [Usage](#usage)",
        "#gh-dark-mode-only)",
        "| The main window (photo by Luke Chesser on Unsplash) |",
        "> [!TIP]",
        "<details>",
        "| cache.ttl | `3600` |",
        "| `DEMO_PORT` | `8080` |",
        "| `demo-tool` | `demo_tool.cli:main` |",
        "### [1.4.0]",
        "[demo-tool-gui](https://github.com/octocat/demo-tool-gui)",
        "github.com/octocat.png?size=48",
        "shadows the packaged one",
        "[MIT](https://spdx.org/licenses/MIT.html)",
        "photo-1518770660439-4636190af475",
        "*Photo by [Alexandre Debi",
    ],
    "rust-cli": [
        "# ferrous-cli",
        "cargo install ferrous-cli",
        "badge/crates.io-v1.0.0-orange?logo=rust",
        "[Release](https://img.shields.io/github/v/release/octocat/ferrous-cli)",
    ],
    "go-cli": [
        "# gopher-cli",
        "go install github.com/octocat/gopher-cli@latest",
        "badge/go.dev-reference-00ADD8?logo=go",
    ],
    "dotnet-tool": [
        "# DotTool.Cli",
        "dotnet tool install --global DotTool.Cli",
        "badge/nuget-v2.1.0-004880?logo=nuget",
    ],
    "node-cli": [
        "# brewkit",
        "npm install brewkit",
        "[![npm](https://img.shields.io/npm/v/brewkit)]",
    ],
    "config-only": [
        "# Config Only",
        "badge/docs-latest-success?logo=readthedocs&style=flat-square",
        "Chat-Matrix-0DBD8B",
        "buymeacoffee.com/octocat",
        "<sub>Editor, light and dark (photos by Domenico Loia and Mohammad Rahmani",
        "pip install config-only",
        "> [!NOTE]",
        "Apache-2.0",
        "photo-1761141535933-7f8e9f468865",
        "Tao Yuan",
    ],
}


@pytest.mark.parametrize("name", sorted(EXPECTATIONS))
def test_example_renders(name):
    root = EXAMPLES / name
    cfg = resolve(root)
    result = Renderer(root, cfg, user_templates=root / "no-user-templates").render()
    for fragment in EXPECTATIONS[name]:
        assert fragment in result.text, fragment
    unexpected = [w for w in result.warnings if "cli_help" not in w]
    assert unexpected == []
    committed = (root / "README.md").read_text()
    assert committed.startswith("<!-- generated by readwright")
    if name in TEMPLATELESS:
        assert not (root / "README.md.j2").exists() and result.template_name == "base.md.j2"
        assert committed == result.text
