from pathlib import Path

import pytest

from mkreadme.config import resolve
from mkreadme.renderer import Renderer

EXAMPLES = Path(__file__).resolve().parent.parent / "examples"
EXPECTATIONS = {
    "kitchen-sink": [
        "# demo-tool",
        "style=flat-square",
        "ko-fi.com/octocat",
        "- [Usage](#usage)",
        "<picture>",
        "<sub>The main window</sub>",
        "> [!TIP]",
        "<details>",
        "| cache.ttl | `3600` |",
        "| `DEMO_PORT` | `8080` |",
        "| `demo-tool` | `demo_tool.cli:main` |",
        "### [1.4.0]",
        "[demo-tool-gui](https://github.com/octocat/demo-tool-gui)",
        "github.com/octocat.png?size=48",
        "shadows the packaged one",
        "[MIT](https://spdx.org/licenses/MIT.html)",
        "photo-1518770660439-4636190af475",
        'Photo by <a href="https://unsplash.com/@alexkixa?utm_source=demo-tool',
    ],
    "minecraft-mod": [
        "# HeadGlance",
        "modrinth/dt/headglance",
        "curseforge/dt/123456",
        "Minecraft 1.21.1",
        "| `neoforge` | required |",
    ],
    "ha-card": [
        "# Motion Card",
        "HACS-Custom",
        "2024.6.0%2B",
        "my.home-assistant.io/redirect/hacs_repository/?owner=octocat",
        "type: custom:motion-card",
    ],
    "flow-plugin": ["# Discord Flow", "pm install Discord Flow", "Type `dc`"],
    "config-only": [
        "# Config Only",
        "badge/docs-latest-success?logo=readthedocs&style=flat-square",
        "Chat-Matrix-0DBD8B",
        "buymeacoffee.com/octocat",
        "<sub>Editor (light and dark)</sub>",
        "pip install config-only",
        "> [!NOTE]",
        "Apache-2.0",
        "photo-1761141535933-7f8e9f468865",
        "Tao Yuan",
    ],
}


@pytest.mark.parametrize("name", sorted(EXPECTATIONS))
def test_example_renders(name):
    root = EXAMPLES / name
    cfg = resolve(root)
    result = Renderer(root, cfg, user_templates=root / "no-user-templates").render()
    for fragment in EXPECTATIONS[name]:
        assert fragment in result.text, fragment
    unexpected = [w for w in result.warnings if "cli_help" not in w]
    assert unexpected == []
    committed = (root / "README.md").read_text()
    assert committed.startswith("<!-- generated by mkreadme")
    if name == "config-only":
        assert not (root / "README.md.j2").exists() and result.template_name == "base.md.j2"
        assert committed == result.text
